services:
  minio:
    image: minio/minio
    container_name: evenement-minio
    command: server /data --console-address ":5050"
    ports:
      - 9000:9000
      - 5050:5050
    environment:
      MINIO_ROOT_USER: minio-access-key
      MINIO_ROOT_PASSWORD: minio-secret-key
    volumes:
      - minio-data:/data

volumes:
  minio-data:
